name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Pnpm install
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Prettier
        run: pnpm prettier

      - name: Eslint
        run: pnpm eslint
